services:
  db:
    image: postgres:15
    container_name: pg_container
    environment:
      POSTGRES_USER: filipjevtovic
      POSTGRES_PASSWORD: aidigitalpass123
      POSTGRES_DB: aidigitaldb
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: python_app
    depends_on:
      - db
    environment:
      DB_USER: filipjevtovic
      DB_PASSWORD: aidigitalpass123
      DB_NAME: aidigitaldb
      DB_HOST: db
      DB_PORT: 5432
    volumes:
      - ./app:/app
    command: [ "python", "main.py" ]

volumes:
  pgdata:
