services:
  db:
    image: postgres:15
    container_name: pg_container
    environment:
      POSTGRES_USER: filipjevtovic
      POSTGRES_PASSWORD: aidigitalpass123
      POSTGRES_DB: aidigitaldb
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  etl:
    build: .
    container_name: etl_app
    environment:
      DB_USER: filipjevtovic
      DB_PASSWORD: aidigitalpass123
      DB_NAME: aidigitaldb
      DB_HOST: db
      DB_PORT: 5432
    volumes:
      - ./app:/app
    command: [ "python", "main.py" ]
    depends_on:
      - db

  dash:
    build: .
    container_name: dash_app
    ports:
      - "8050:8050"
    environment:
      DB_USER: filipjevtovic
      DB_PASSWORD: aidigitalpass123
      DB_NAME: aidigitaldb
      DB_HOST: db
      DB_PORT: 5432
    volumes:
      - ./app:/app
    command: [ "python", "visualization.py" ]
    depends_on:
      - db

volumes:
  pgdata:
